import type { Metadata } from "next";
import { GeistMono, GeistSans } from "geist/font";

import "./globals.css";

import { cn } from "~/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* Apply GeistMono and GeistSans as tailwind variable and set GeistSans as default font. */}
      <body className={cn(GeistSans.variable, GeistMono.variable, GeistSans.className)}>
        {children}
      </body>
    </html>
  );
}
